
BLENDER="C:\Program Files\Blender Foundation\Blender 4.2.1\blender.exe"
DIST=../dist

all : \
    $(DIST)/vignette.pnct \
    $(DIST)/vignette.scene \

$(DIST)/vignette.scene : vignette.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "vignette.blend" "$(DIST)/vignette.scene"

$(DIST)/vignette.pnct : vignette.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "vignette.blend" "$(DIST)/vignette.pnct" 
